<?php

/**
 *
 * This module provides several pages for the Hapus PDF gen app.
 *
 * This version is for Drupal 7.
 *
 */

/**
 * Implements hook_menu().
 */
function hapus_pages_menu() {
  //The Dashboard and user reports
  $items['user/dashboard'] = array(
   'title' => 'Dashboard',
   'description' => 'Your Dashboard',
   'page callback' => 'render_hapus_reports',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc'
  );

  //The Pricing menu
  $items['Pricing/pricing_table'] = array(
   'title' => 'Pricing table',
   'description' => 'Pricing table',
   'page callback' => 'render_hapus_pricing_table',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-pricing-menu',
   'weight' => -50
  );

  //The Documentation menu
  $items['Documentation/API'] = array(
   'title' => 'API',
   'description' => 'Sprint PDF API documentation',
   'page callback' => 'render_hapus_documentation',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-documentation-menu',
   'weight' => 1
  );
  $items['Documentation/options'] = array(
   'title' => 'PDF options',
   'description' => 'Sprint PDF page generation options',
   'page callback' => 'render_hapus_documentation',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-documentation-menu',
   'weight' => 2
  );
  $items['Documentation/page_options'] = array(
   'title' => 'Page sizes',
   'description' => 'Sprint PDF page size options',
   'page callback' => 'render_hapus_documentation',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-documentation-menu',
   'weight' => 3
  );
  $items['Documentation/font_list'] = array(
   'title' => 'Font list',
   'description' => 'All currently supported fonts',
   'page callback' => 'render_hapus_documentation',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-documentation-menu',
   'weight' => 4
  );

  //Login/logout links
  $items['sprintpdf_login'] = array(
    'title' => 'Log in',
    'access callback' => 'user_is_anonymous',
    'page callback' => 'sprintpdf_redirect_login_page',
    'file' => 'hapus_pages.inc',
    'menu_name' => 'main-menu',
    'weight' => 50
  );
  $items['sprintpdf_logout'] = array(
    'title' => 'Log out',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'user_logout',
    'file' => 'user.pages.inc',
    'file path' => drupal_get_path('module', 'user'),
    'menu_name' => 'main-menu',
    'weight' => 50
  );


  //The Features menu
  $items['Features/pricing'] = array(
   'title' => 'Sprint PDF Pricing',
   'description' => 'Pricing features for Sprint PDF',
   'page callback' => 'render_hapus_features',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-features-menu',
   'weight' => 1
  );
  

  //Stand alones-->API examples page
  $items['api-example'] = array(
   'title' => 'API example',
   'description' => 'API example',
   'page callback' => 'render_hapus_api_example',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc'
  );

  //Stand alones-->*Try it* page
  $items['try-it'] = array(
   'title' => 'Try it',
   'description' => 'Try out Sprint PDF',
   'page callback' => 'render_hapus_try_it',
   'access arguments' => array('access content'),
   'file' => 'hapus_pages.inc',
   'menu_name' => 'menu-main-menu',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function hapus_pages_theme() {
  return array(
    //Pricing pages
    'pricing_table' => array(
      'template' => 'templates/pricing_table',
    ),
    //Stand-alone pages
    'api-example' => array(
      'template' => 'templates/api_example',
    ),
    'try-it' => array(
      'template' => 'templates/try_it',
    ),
    //Documentation pages
    'api' => array(
      'template' => 'templates/api',
    ),
    'gen-options' => array(
      'template' => 'templates/gen-options',
    ),
    'page-options' => array(
      'template' => 'templates/page-options',
    ),
    'font-list' => array(
      'template' => 'templates/font-list',
    ),
    //Reports and user related pages
    'dashboard' => array(
      'template' => 'templates/dashboard',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function hapus_pages_form_alter(&$form, &$form_state, $form_id) {
  if(in_array($form_id, array('user_login', 'user_register_form'))){
    drupal_set_title("Login now");
    drupal_add_css(drupal_get_path('module', 'hapus_pages') . '/css/hapus_login.css');
  }
}